server:
    port: 8080

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/kmpjh;DB_CLOSE_DELAY=-1
        username: kmpjh
        password:

partner:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://13.125.250.135:5432/bitcoin_core_testnet
        username: postgres
        password: "password"
        driver-class-name: org.postgresql.Driver
