spring:
  profiles: default

datasource:
  bch-testnet:
      initialize: true
      driver-class-name: "org.postgresql.Driver"
      url: "jdbc:postgresql://13.125.250.135:5432/bitcoin_core_testnet"
      user-name: "postgres"
      password: "##free@2018.."
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000